import type { Category, DeliveryZone, Extra, Product, Promotion, PublicData, RestaurantSettings } from "./types";

const now = new Date().toISOString();

export const demoSettings: RestaurantSettings = {
  id: "00000000-0000-4000-8000-000000000001",
  business_name: "Sabor Express",
  slogan: "Tu antojo, en camino",
  logo_url: null,
  hero_image_url:
    "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1600&q=85",
  phone: "+595 61 500 000",
  whatsapp_number: "595981123456",
  address: "Av. San Blas, Ciudad del Este, Paraguay",
  map_url: "https://maps.google.com/?q=Ciudad+del+Este+Paraguay",
  instagram_url: "https://instagram.com/",
  facebook_url: "https://facebook.com/",
  tiktok_url: "https://tiktok.com/",
  opening_hours: "Lunes a domingo de 10:30 a 23:30",
  delivery_enabled: true,
  pickup_enabled: true,
  delivery_fee: 10000,
  minimum_order_for_delivery: 30000,
  primary_color: "#e84c1f",
  secondary_color: "#ffc247",
  save_orders_enabled: true,
  allow_cash_payment: true,
  allow_transfer_payment: true,
  allow_card_on_delivery: true,
  currency: "PYG",
  timezone: "America/Asuncion",
  is_open: true,
  accepting_orders: true,
  created_at: now,
  updated_at: now,
};

export const demoCategories: Category[] = [
  ["cat-hamburguesas", "Hamburguesas", "hamburguesas", "Carnes jugosas, panes suaves y salsas de la casa.", "Burger"],
  ["cat-pizzas", "Pizzas", "pizzas", "Pizzas artesanales con bordes dorados.", "Pizza"],
  ["cat-lomitos", "Lomitos", "lomitos", "Clasicos paraguayos bien cargados.", "Sandwich"],
  ["cat-combos", "Combos", "combos", "Opciones para compartir y ahorrar.", "BadgePercent"],
  ["cat-bebidas", "Bebidas", "bebidas", "Gaseosas, aguas y bebidas frias.", "CupSoda"],
  ["cat-postres", "Postres", "postres", "Dulces finales para completar el pedido.", "IceCream"],
  ["cat-promociones", "Promociones", "promociones", "Ofertas activas por tiempo limitado.", "Sparkles"],
].map(([id, name, slug, description, icon], index) => ({
  id,
  name,
  slug,
  description,
  image_url: null,
  icon,
  display_order: index + 1,
  is_active: true,
  created_at: now,
}));

export const demoExtras: Extra[] = [
  { id: "extra-queso", name: "Queso extra", price: 5000, is_active: true, created_at: now },
  { id: "extra-huevo", name: "Huevo", price: 4000, is_active: true, created_at: now },
  { id: "extra-bacon", name: "Bacon", price: 7000, is_active: true, created_at: now },
  { id: "extra-salsa", name: "Salsa extra", price: 3000, is_active: true, created_at: now },
  { id: "extra-papas", name: "Papas adicionales", price: 10000, is_active: true, created_at: now },
];

const productImages = {
  burger: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85",
  bacon: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=900&q=85",
  pizza: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=900&q=85",
  pepperoni: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=900&q=85",
  lomito: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=85",
  combo: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=900&q=85",
  soda: "https://images.unsplash.com/photo-1581636625402-29b2a704ef13?auto=format&fit=crop&w=900&q=85",
  water: "https://images.unsplash.com/photo-1616118132534-381148898bb4?auto=format&fit=crop&w=900&q=85",
  brownie: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=85",
  cheesecake: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=900&q=85",
};

export const demoProducts: Product[] = [
  {
    id: "prod-burger-clasica",
    category_id: "cat-hamburguesas",
    name: "Hamburguesa Clasica",
    slug: "hamburguesa-clasica",
    short_description: "Carne smash, queso, lechuga, tomate y salsa express.",
    long_description: "Una hamburguesa honesta y sabrosa con carne grillada, pan brioche, vegetales frescos y salsa especial.",
    base_price: 35000,
    offer_price: null,
    image_url: productImages.burger,
    is_available: true,
    is_featured: true,
    is_best_seller: true,
    is_new: false,
    is_promotion: false,
    display_order: 1,
  },
  {
    id: "prod-burger-bacon",
    category_id: "cat-hamburguesas",
    name: "Hamburguesa Doble Bacon",
    slug: "hamburguesa-doble-bacon",
    short_description: "Doble carne, cheddar, bacon crocante y salsa ahumada.",
    long_description: "Doble medallon de carne con cheddar fundido, bacon crocante, cebolla caramelizada y salsa ahumada.",
    base_price: 52000,
    offer_price: 47000,
    image_url: productImages.bacon,
    is_available: true,
    is_featured: true,
    is_best_seller: true,
    is_new: false,
    is_promotion: true,
    display_order: 2,
  },
  {
    id: "prod-pizza-muzarella",
    category_id: "cat-pizzas",
    name: "Pizza Muzarella",
    slug: "pizza-muzarella",
    short_description: "Masa artesanal, salsa de tomate y mucha muzarella.",
    long_description: "Pizza clasica con masa fermentada, salsa casera, oregano y abundante muzarella gratinada.",
    base_price: 65000,
    offer_price: null,
    image_url: productImages.pizza,
    is_available: true,
    is_featured: true,
    is_best_seller: false,
    is_new: false,
    is_promotion: false,
    display_order: 3,
  },
  {
    id: "prod-pizza-pepperoni",
    category_id: "cat-pizzas",
    name: "Pizza Pepperoni",
    slug: "pizza-pepperoni",
    short_description: "Pepperoni, queso fundido y borde dorado.",
    long_description: "Una pizza intensa con pepperoni laminado, salsa de tomate especiada y queso fundido.",
    base_price: 78000,
    offer_price: null,
    image_url: productImages.pepperoni,
    is_available: true,
    is_featured: false,
    is_best_seller: true,
    is_new: true,
    is_promotion: false,
    display_order: 4,
  },
  {
    id: "prod-lomito-arabe",
    category_id: "cat-lomitos",
    name: "Lomito Arabe",
    slug: "lomito-arabe",
    short_description: "Pan arabe, carne, vegetales, queso y salsa de ajo.",
    long_description: "Lomito envuelto en pan arabe con carne tierna, vegetales frescos, queso y salsa de ajo.",
    base_price: 42000,
    offer_price: null,
    image_url: productImages.lomito,
    is_available: true,
    is_featured: false,
    is_best_seller: true,
    is_new: false,
    is_promotion: false,
    display_order: 5,
  },
  {
    id: "prod-lomito-completo",
    category_id: "cat-lomitos",
    name: "Lomito Completo",
    slug: "lomito-completo",
    short_description: "Carne, jamon, queso, huevo, ensalada y papas.",
    long_description: "El clasico completo con carne grillada, jamon, queso, huevo, vegetales y papas.",
    base_price: 48000,
    offer_price: null,
    image_url: productImages.lomito,
    is_available: true,
    is_featured: false,
    is_best_seller: false,
    is_new: false,
    is_promotion: false,
    display_order: 6,
  },
  {
    id: "prod-combo-familiar",
    category_id: "cat-combos",
    name: "Combo Familiar",
    slug: "combo-familiar",
    short_description: "2 hamburguesas, pizza muzza, papas grandes y bebida.",
    long_description: "Combo generoso para compartir: dos hamburguesas clasicas, una pizza muzarella, papas grandes y bebida de 1.5L.",
    base_price: 155000,
    offer_price: 139000,
    image_url: productImages.combo,
    is_available: true,
    is_featured: true,
    is_best_seller: false,
    is_new: false,
    is_promotion: true,
    display_order: 7,
  },
  {
    id: "prod-combo-pareja",
    category_id: "cat-combos",
    name: "Combo Pareja",
    slug: "combo-pareja",
    short_description: "2 lomitos completos, papas medianas y 2 bebidas.",
    long_description: "Ideal para dos: dos lomitos completos, una porcion de papas medianas y dos bebidas.",
    base_price: 98000,
    offer_price: 89000,
    image_url: productImages.combo,
    is_available: true,
    is_featured: false,
    is_best_seller: false,
    is_new: false,
    is_promotion: true,
    display_order: 8,
  },
  {
    id: "prod-coca",
    category_id: "cat-bebidas",
    name: "Coca-Cola 500 ml",
    slug: "coca-cola-500-ml",
    short_description: "Bien fria.",
    long_description: "Coca-Cola 500 ml servida fria para acompanar tu pedido.",
    base_price: 8000,
    offer_price: null,
    image_url: productImages.soda,
    is_available: true,
    is_featured: false,
    is_best_seller: false,
    is_new: false,
    is_promotion: false,
    display_order: 9,
  },
  {
    id: "prod-agua",
    category_id: "cat-bebidas",
    name: "Agua mineral",
    slug: "agua-mineral",
    short_description: "Botella 500 ml.",
    long_description: "Agua mineral sin gas en botella de 500 ml.",
    base_price: 6000,
    offer_price: null,
    image_url: productImages.water,
    is_available: true,
    is_featured: false,
    is_best_seller: false,
    is_new: false,
    is_promotion: false,
    display_order: 10,
  },
  {
    id: "prod-brownie",
    category_id: "cat-postres",
    name: "Brownie con helado",
    slug: "brownie-con-helado",
    short_description: "Brownie tibio con bocha de helado.",
    long_description: "Brownie humedo de chocolate servido tibio con helado de crema americana.",
    base_price: 28000,
    offer_price: null,
    image_url: productImages.brownie,
    is_available: true,
    is_featured: true,
    is_best_seller: false,
    is_new: true,
    is_promotion: false,
    display_order: 11,
  },
  {
    id: "prod-cheesecake",
    category_id: "cat-postres",
    name: "Cheesecake",
    slug: "cheesecake",
    short_description: "Porcion cremosa con salsa de frutos rojos.",
    long_description: "Cheesecake suave con base crocante y salsa artesanal de frutos rojos.",
    base_price: 26000,
    offer_price: null,
    image_url: productImages.cheesecake,
    is_available: true,
    is_featured: false,
    is_best_seller: false,
    is_new: false,
    is_promotion: false,
    display_order: 12,
  },
].map((product) => ({
  ...product,
  created_at: now,
  updated_at: now,
  categories: demoCategories.find((category) => category.id === product.category_id) ?? null,
  product_variants: [
    { id: `${product.id}-var-mediano`, product_id: product.id, name: "Mediano", price_modifier: 0, is_required: false, created_at: now },
    { id: `${product.id}-var-grande`, product_id: product.id, name: "Grande", price_modifier: product.category_id === "cat-bebidas" ? 4000 : 12000, is_required: false, created_at: now },
  ],
  product_extras: demoExtras.map((extra) => ({ extras: extra })),
}));

export const demoPromotions: Promotion[] = [
  {
    id: "promo-combo-familiar",
    title: "Combo Familiar Express",
    description: "Ahorra con una seleccion completa para compartir en casa.",
    image_url: productImages.combo,
    promo_price: 139000,
    original_price: 155000,
    starts_at: null,
    ends_at: null,
    is_active: true,
    linked_product_id: "prod-combo-familiar",
    created_at: now,
  },
  {
    id: "promo-bacon",
    title: "Doble Bacon en oferta",
    description: "La favorita de la casa con precio especial por tiempo limitado.",
    image_url: productImages.bacon,
    promo_price: 47000,
    original_price: 52000,
    starts_at: null,
    ends_at: null,
    is_active: true,
    linked_product_id: "prod-burger-bacon",
    created_at: now,
  },
];

export const demoZones: DeliveryZone[] = [
  { id: "zone-centro", name: "Centro", fee: 8000, minimum_order: 25000, is_active: true, display_order: 1 },
  { id: "zone-area-1", name: "Area 1", fee: 10000, minimum_order: 30000, is_active: true, display_order: 2 },
  { id: "zone-km4", name: "Km 4", fee: 12000, minimum_order: 35000, is_active: true, display_order: 3 },
  { id: "zone-presidente-franco", name: "Presidente Franco", fee: 18000, minimum_order: 50000, is_active: true, display_order: 4 },
];

export const demoPublicData: PublicData = {
  settings: demoSettings,
  categories: demoCategories,
  products: demoProducts,
  promotions: demoPromotions,
  zones: demoZones,
};
